### PR TITLE
DNS lookup of .local names

### PR DESCRIPTION
**Pull request by eikeon**
I'm trying to get lookup working for .local names in my App. The lookup for global names is working fine, but not the lookup for any of the .local names on my network.

I tried to install avahi-daemon from the deps.sh but guessing that's being called from within a docker container?

### CODE REVIEW

**Comment by Page-** [comment]
This would be being called when building the docker image, so not actually being run on the device (we cross compile on our servers, since if you've ever tried to build on a raspberry pi or similar you'll realise it's not exactly a quick process ;)  )

The way to do this would be to change the start script in package.json from `"start": "node hello.js"` to `"start": "/etc/init.d/avahi-daemon restart && node hello.js"`

**Comment by eikeon** [comment]
Ah that makes sense. I've done that and now need to debug why it's failing to start. From the Logs tab:

> /etc/init.d/avahi-daemon start && node hello.js
[....] Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon?25lG[FAIL?12l?25h failed!

**Comment by eikeon** [comment]
Seems like I might be running into: https://github.com/lxc/lxc/issues/25#issuecomment-28304487

**Comment by Page-** [comment]
Check out https://github.com/nghiant2710/avahi-example  (if you haven't already got this working)

**Comment by eikeon** [comment]
Perfect, thank you.

Is the Dockerfile used in basic-resin-node-project available for reference? resin/rpi-nodejs? I'd like to switch to using a Dockerfile to integrate the above – unless that's no the recommended course of action.

**Comment by eikeon** [comment]
I'll key off of this unless there's a better starting point: https://github.com/nghiant2710/resin-docker-with-NodeJS-Apache-MySQL-PHP/blob/master/Dockerfile

**Comment by Page-** [comment]
Check out https://registry.hub.docker.com/u/resin/rpi-node/tags/manage/ which is a clone of https://registry.hub.docker.com/_/node/ designed to run on the raspberry pi (armhf)

@shaunmulligan may also be able to point to an example use

**Comment by techniq** [comment]
I setup my `Dockerfile` and `start.sh` like the `avahi-example` project, but I still can not resolve any mDNS names from the container, or ping the container using it's mDNS name (I setup `foo` as my hostname in `avahi-daemon.conf`.  

```
$ docker run -it --rm docker-avahi
[ ok ] Restarting Avahi mDNS/DNS-SD Daemon: avahi-daemon.
root@53dc8911e867:/# avahi-resolve-host-name foo.local
Failed to create client object: Daemon not running
root@53dc8911e867:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.2  20040  2896 ?        Ss   16:51   0:00 /bin/bash start.sh
avahi       15  0.0  0.2  32092  2536 ?        S    16:51   0:00 avahi-daemon: running [53dc8911e867.local]
avahi       16  0.0  0.0  32092   252 ?        S    16:51   0:00 avahi-daemon: chroot helper
root        34  0.0  0.3  20236  3276 ?        S    16:51   0:00 bash
root        36  0.0  0.2  17492  2048 ?        R+   18:24   0:00 ps aux
```

Any ideas?

**Comment by petrosagg** [comment]
I think that you need to use `--net=host` so that the avahi-daemon indeed broadcasts the hostnames to the network.

**Comment by eikeon** [comment]
What's your Dockerfile look like? Base image? It's working for me on a BBB with [this Dockerfile] (https://gist.github.com/eikeon/b7bc4f05119f0143ead5) when I `git push -f resin master`

**Comment by petrosagg** [comment]
@eikeon docker containers on the resin platform have the `--net=host` flag set.

**Comment by techniq** [comment]
@petrosagg - THANK YOU!  `--net=host` was it.  I'm actually setting up a Docker container to run my ansible playbooks for some BBB, and the BBB are resolved uisng mDNS (they run Avahi).

**Comment by petrosagg** [comment]
You're welcome :)

**Pull request closed without merging**
